# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - adservice.yaml
 - cartservice.yaml
 - checkoutservice.yaml
 - currencyservice.yaml
 - emailservice.yaml
 - frontend.yaml
# - loadgenerator.yaml # During development, the loadgenerator module inside skaffold.yaml will be used.
 - paymentservice.yaml
 - productcatalogservice.yaml
 - recommendationservice.yaml
 - shippingservice.yaml
# components:
# - ../kustomize/components/cymbal-branding
# - ../kustomize/components/google-cloud-operations
# - ../kustomize/components/memorystore
# - ../kustomize/components/network-policies
# - ../kustomize/components/alloydb
# - ../kustomize/components/shopping-assistant
# - ../kustomize/components/spanner
# - ../kustomize/components/container-images-tag
# - ../kustomize/components/container-images-tag-suffix
# - ../kustomize/components/container-images-registry
images:
resources:
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - loadgenerator.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - shippingservice.yaml

images:
  - name: adservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/adservice
    newTag: "1"

  - name: cartservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/cartservice
    newTag: "3"

  - name: checkoutservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/checkoutservice
    newTag: "1"

  - name: currencyservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/currencyservice
    newTag: "1"

  - name: emailservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/emailservice
    newTag: "1"

  - name: frontend
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/frontend
    newTag: "29"

  - name: loadgenerator
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/loadgenerator
    newTag: "1"

  - name: paymentservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/paymentservice
    newTag: "1"

  - name: productcatalogservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/productcatalogservice
    newTag: "1"

  - name: recommendationservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/recommendationservice
    newTag: "2"

  - name: shippingservice
    newName: 283236069347.dkr.ecr.ap-southeast-1.amazonaws.com/sap2506/shippingservice
    newTag: "2"
    
# DÁN ĐOẠN PATCH CHUẨN NÀY VÀO ĐÁY FILE THAY CHO ĐOẠN CŨ:
patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all-deployments
      spec:
        template:
          spec:
            imagePullSecrets:
              - name: regcred
